name: blackjack-api
app: node@18
options:
  env:
    - name: NODE_ENV
      value: production
    - name: PORT
      value: "3000"
    - name: DB_HOST
      value: ${DB_HOST}
    - name: DB_PORT
      value: ${DB_PORT}
    - name: DB_USER
      value: ${DB_USER}
    - name: DB_PASSWORD
      value: ${DB_PASSWORD}
    - name: DB_NAME
      value: ${DB_NAME}
    - name: CORS_ORIGINS
      value: https://hanmj97.github.io
  install: npm ci --omit=dev
  start: npm start
  build: ""
  ports: 3000
